<?php
/**
 * @var string $baseUrl
 * @var string $form_post_path
 * @var \Entities\Organization $organization
 * @var \Entities\Webhook[] $webhooks
 * @var \Services\Authentication\Authenticate $auth
*/
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-star"></i>Webhooks</h2>
</div>

<!-- Start body content -->
<div class="body-content animated fadeIn">

    <div class="row">
        <div class="col-md-12">
            <p>
                Webhooks provide a way to configure the Marketplace to make requests to your server
                whenever certain events occur.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Webhooks
                </div>
                <div class="panel-body">
                    <table class="table table-bordered webhook-table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>URL</th>
                            <th>Logs</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($webhooks as $webhook) : ?>
                            <?php $isDisabled = $webhook->isImmutable() == 1 ? 'disabled' : ''; ?>
                            <tr>
                                <td><?= $webhook->getTitle(); ?></td>
                                <td><?= $webhook->getUrl(); ?></td>
                                <td>
                                    <a href="/organization/<?= $organization->getUniqueId(); ?>/webhooks/<?= $webhook->getId(); ?>">
                                        View Requests
                                    </a>
                                </td>
                                <td class="align-right">
                                    <a href="/organization/<?= $organization->getUniqueId(); ?>/webhooks/<?= $webhook->getId(); ?>/webhook-view"
                                       class="btn btn-default btn-sm edit-modal <?= $isDisabled;?>">Edit
                                    </a>
                                </td>
                                <td class="align-right">
                                    <a href="/organization/<?= $organization->getUniqueId(); ?>/webhooks/<?= $webhook->getId(); ?>/delete"
                                       class="btn btn-default btn-sm delete-webhook <?= $isDisabled;?>">Delete
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            <div class="errors"></div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Add new webhook
                </div>
                <div class="panel-body">
                    <form name="webhook"
                          action="/organization/<?= $organization->getUniqueId(); ?>/webhooks"
                          method="post">
                        <input type="hidden"
                               name="organization_id"
                               value="<?= $organization->getId(); ?>"/>

                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Title <span><strong>*</strong></span></label>
                                <input class="form-control"
                                       name="title"
                                       value=""
                                       required
                                />
                                <span class="help-block">
                        Short Description for this webhook.
                    </span>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>URL <span><strong>*</strong></span></label>
                                <input class="form-control"
                                       name="url"
                                       value=""
                                       required
                                />
                                <span class="help-block">
                        The URL to post the event data to.
                    </span>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Username</label>
                                <input class="form-control"
                                       name="username"
                                       value=""/>
                                <span class="help-block">
                        Optional Username if URL requires basic authentication.
                    </span>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password"
                                       class="form-control"
                                       name="password"
                                       value=""/>
                                <span class="help-block">
                        Optional Password if URL requires basic authentication.
                    </span>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Active</label>
                                <input type="checkbox" name="active">
                            </div>
                        </div>
                        <?php if($auth->getUser()->getRole() == 'superadmin' ):?>
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Immutable</label>
                                <input type="checkbox" name="immutable" value="1">
                            </div>
                        </div>
                        <?php endif;?>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Trigger</label>
                                <select name="event" class="form-control">
                                    <option value="Transaction.create">Transaction Created</option>
                                </select>
                                <span class="help-block">
                        The event which triggers the webhook.
                    </span>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <button class="btn btn-default" data-toggle="tooltip" data-placement="left"
                                    title="Save Webhook">Save
                            </button>
                            <a href="/organization" style="margin-left: 20px;" data-toggle="tooltip"
                               data-placement="right" title="Cancel Webhook">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="editWebhookModal" tabindex="-1" role="dialog" aria-labelledby="editWebhookModalModal">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Edit Webhook: <span class="id"></span></h4>
            </div>
            <div class="modal-body">
                <div class="row webhook-edit">

                    <div class="col-md-12">

                        <div class="errors"></div>

                        <div class="panel panel-default">
                            <div class="panel-body">
                                <form name="webhook-edit"
                                      action=""
                                      method="post">
                                    <input type="hidden"
                                           name="organization_id"
                                           value=""/>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label>Title <span><strong>*</strong></span></label>
                                            <input class="form-control"
                                                   name="title"
                                                   value=""
                                                   required
                                            />
                                            <span class="help-block">
                        Short Description for this webhook.
                    </span>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label>URL <span><strong>*</strong></span></label>
                                            <input class="form-control"
                                                   name="url"
                                                   value=""
                                                   required
                                            />
                                            <span class="help-block">
                        The URL to post the event data to.
                    </span>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input class="form-control"
                                                   name="username"
                                                   value=""/>
                                            <span class="help-block">
                        Optional Username if URL requires basic authentication.
                    </span>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password"
                                                   class="form-control"
                                                   name="password"
                                                   value=""/>
                                            <span class="help-block">
                        Optional Password if URL requires basic authentication.
                    </span>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label>Active</label>
                                            <input type="checkbox" name="active">
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label>Trigger</label>
                                            <select name="event" class="form-control">
                                                <option value="Transaction.create">Transaction Created</option>
                                            </select>
                                            <span class="help-block">
                        The event which triggers the webhook.
                    </span>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button style="background-color: red" type="button" class="btn btn-default btn-sm pull-left modal-close" data-dismiss="modal">
                                            <span style="color: white">Cancel</span>
                                        </button>
                                        <button style="background-color: #81B71A" class="btn btn-default pull-right" data-toggle="tooltip" data-placement="left" title="Save Webhook">
                                            <span style="color: white">Save</span>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
