<?php
/**
 * @var string $baseUrl
 * @var \Entities\Webhook $webhook
 * @var \MongoDB\Model\BSONDocument $log
 */

?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-star"></i>Request Details</h2>
</div>

<!-- Start body content -->
<div class="body-content animated fadeIn">
    <div class="row">
        <div class="col-md-12">
            <h1><?= $webhook->getTitle(); ?> Request Details</h1>
        </div>
        <div class="col-md-12">
            <strong>URL: </strong> <?= $webhook->getUrl(); ?>
        </div>
        <div class="col-md-12">
            <strong>Trigger: </strong> <?= $webhook->getEvent(); ?>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-12">
            <ul>
                <li>
                    <strong>HTTP Status:</strong>
                    <?= $log['http_status']; ?>
                    <?php if (!in_array($log['http_status'], [200, 201])) : ?>
                        <i id="replay_webhook_log"
                           data-organization="<?= $organization->getUniqueId(); ?>"
                           data-webhook_log_id="<?= $log['_id']; ?>"
                           data-webhook_id="<?= $webhook->getId(); ?>"
                           class="fa fa-refresh"
                        >
                        </i>
                    <?php endif; ?>
                </li>
                <li>
                    <strong>Request Time:</strong>
                    <?= $log['request_time']['date']; ?>
                    <?= $log['request_time']['timezone']; ?>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h2>Request</h2>
                    </div>
                </div>
                <div class="panel-body">
                    <h3>Headers</h3>
                    <table class="table">
                        <?php foreach ($log['request']['headers'] as $name => $value) : ?>
                            <?php if ($name == 'Authorization') {
                                $value = "REDACTED";
                            } ?>
                            <tr>
                                <td>
                                    <?= $name; ?>
                                </td>
                                <td>
                                    <?= $value; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>

                    <h3>Body</h3>
                    <div class="codeview">
                        <pre><?= json_encode(
                                json_decode(
                                    $log['request']['body']
                                ),
                                JSON_PRETTY_PRINT
                            ); ?></pre>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h1>Response</h1>
    <div class="row">
        <?php foreach ($log['responses'] as $key => $response) : ?>

            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h2>Response <?= $key; ?></h2>
                        </div>
                    </div>
                    <div class="panel-body">
                        <?php if (!empty($response['headers'])) : ?>
                            <h3>Headers</h3>
                            <table class="table">
                                <?php foreach ($response['headers'] as $name => $value) : ?>
                                    <tr>
                                        <td>
                                            <?= $name; ?>
                                        </td>
                                        <td>
                                            <?php foreach ($value as $aFrigginValue) : ?>
                                                <?= $aFrigginValue; ?> <br/>
                                            <?php endforeach; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </table>

                            <h3>Body</h3>
                            <div class="codeview">
                                <pre><?= $response['body']; ?></pre>
                            </div>

                        <?php elseif (!empty($log['response'])) : ?>
                            <?= $log['response']; ?>
                        <?php endif; ?>

                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

</div>