<?php
/** @var string $baseUrl */
/** @var string $type */
/** @var \Entities\Participant $participant */
/** @var \Entities\Adjustment[] $adjustments */
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-users"></i>Participant Activity</h2>
</div>
<!-- Start body content -->
<div class="body-content animated fadeIn">
    <div class="text-right">
        <div class="btn-group">
            <a class="btn btn-primary" href="<?= '/participant';?>">
                <?=_("Back to participant listing");?>
            </a>
        </div>
    </div>

    <br />


    <div class="row">

        <div class="col-xs-12">
            <div class="participant-listing">
                <div class="table-responsive table-color">
                    <table class="table hover">
                        <thead>
                        <tr>
                            <th width="10%">Points</th>
                            <th width="10%">Type</th>
                            <th width="20%">Reference</th>
                            <th width="35%">Description</th>
                            <th width="10%">Transaction ID</th>
                            <th width="15%">Created</th>
                        </tr>
                        </thead>
                        <tbody class="paginated-container">
                        <?php foreach($adjustments as $adjustment):?>
                            <?php
                            $transactionUrl =  '/participant/'
                                . $participant->getUniqueId()
                                . '/transaction/'
                                . $adjustment->getTransactionId();
                            ?>
                            <tr>
                                <td><?=$adjustment->getAmount();?></td>
                                <td><?=$adjustment->getType() === 'credit' ? 'Issued':'Withdrawal';?></td>
                                <td><?=$adjustment->getReference();?></td>
                                <td><?=$adjustment->getDescription();?></td>
                                <td>
                                    <?php if($adjustment->isGeneratedFromTransaction()):?>
                                        <a href="<?=$transactionUrl;?>">
                                            <?=$adjustment->getTransactionId();?>
                                        </a>
                                    <?php endif;?>
                                </td>
                                <td><?=$adjustment->getCreatedAt();?></td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>