<?php
/**
 *
 * @var \Services\Authentication\Authenticate $auth
 * @var string $baseUrl
 * @var string $formAction
 * @var string $formContext update or create
 * @var \Entities\Participant $participant
 */
$updateFormSuccess = _('Participant updated');
$createFormSuccess = _('Participant created. Redirecting...');
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-gears"></i><?=$formContext === 'update' ? 'Update':'Add';?> Participant</h2>
</div>

<!-- Start body content -->
<div class="body-content animated fadeIn">

    <div class="message"></div>
    <form id="participantForm"
          name="participant"
          data-action-type="<?=$formContext;?>"
          data-success-create-message="<?=$createFormSuccess;?>"
          data-success-update-message="<?=$updateFormSuccess;?>"
          action="<?=  $formAction; ?>"
          method="post">

        <fieldset>
            <legend>Participant</legend>


            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Organization <span><strong>*</strong></span></label>
                        <select autocomplete="off"
                                data-validation="required"
                                name="organization"
                                data-offset="30"
                                data-unique-id="true"
                                data-min-characters="0"
                                class="form-control"
                                data-remote="/organization/list?method=json">
                            <?php if($participant->getOrganization() !== null):?>
                            <option selected value="<?=$participant->getOrganization()->getUniqueId();?>"><?=$participant->getOrganization()->getName();?></option>
                            <?php else:?>
                                <option value=""></option>
                            <?php endif;?>
                        </select>
                        <div class="localized-error error-organization"></div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Program <span><strong>*</strong></span></label>
                        <select autocomplete="off"
                                data-validation="required"
                                name="program"
                                data-filter-organization="<?=$participant->getProgram() === null?:$participant->getProgram()->getUniqueId();?>"
                                data-offset="30"
                                data-unique-id="true"
                                data-min-characters="0"
                                class="form-control"
                                data-remote="/program/list?method=json">
                            <?php if($participant->getProgram() !== null):?>
                            <option selected value="<?=$participant->getProgram()->getUniqueId();?>"><?=$participant->getProgram()->getName();?></option>
                            <?php else:?>
                                <option value=""></option>
                            <?php endif;?>
                        </select>
                        <div class="localized-error error-program"></div>
                    </div>
                </div>
                <div class="col-lg-1">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Status <span><strong>*</strong></span></label>
                            <select autocomplete="off" class="form-control" name="active">
                                <option value="1">Active</option>
                                <option <?=$participant->isActive() === true ?:'selected';?> value="0">Inactive</option>
                            </select>
                            <div class="localized-error error-active"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Unique ID <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                               data-validation="required"
                            type="text"
                            class="form-control"
                            name="unique_id" <?=$participant->getId() === null?'':'disabled'?>
                            value="<?=$participant->getUniqueId();?>"
                        />
                        <div class="localized-error error-unique_id"></div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>First Name <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                               data-validation="required"
                            type="text"
                            class="form-control"
                            name="firstname"
                            value="<?=$participant->getFirstname();?>"
                        />
                        <div class="localized-error error-firstname"></div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Last Name <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                               data-validation="required"
                            type="text"
                            class="form-control"
                            name="lastname"
                            value="<?=$participant->getLastname();?>"
                        />
                        <div class="localized-error error-lastname"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-8">
                    <div class="form-group">
                        <label>Email Address <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                               data-validation="email"
                            type="text"
                            class="form-control"
                            name="email_address"
                            value="<?=$participant->getEmailAddress();?>"
                        />
                        <div class="localized-error error-email_address"></div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Birthdate</label>
                        <input autocomplete="off"
                               type="text"
                               value="<?=$participant->getFormattedBirthdate();?>"
                               class="birthdate form-control"
                               name="birthdate"
                               placeholder="MM/DD/YYYY" />
                        <div class="localized-error error-birthdate"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <?php if(in_array($auth->getUser()->getRole(), ['superadmin', 'admin'])):?>
                    <div class="col-xs-12">
                        <hr />
                        <h4>Password (leave blank, unless updating.)</h4>
                        <br />
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Password</label>
                            <input autocomplete="off"
                                   type="text"
                                   class="form-control"
                                   name="password"
                                   minlength="8"
                            />
                            <div class="localized-error error-password"></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Confirm Password</label>
                            <input autocomplete="off"
                                   type="text"
                                   class="form-control"
                                   name="password_confirm"
                                   minlength="8"
                            />
                            <div class="localized-error error-password_confirm"></div>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </fieldset>
        <?php if(in_array($auth->getUser()->getRole(), ['superadmin', 'admin'])):?>
        <div class="footer text-right">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
        <?php endif;?>
        <br/>
    </form>
</div>