<?php
/** @var string $baseUrl */
/** @var \Entities\Participant $participant */
/** @var \Entities\Transaction $transaction */
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-gears"></i>Transaction: <?=$transaction->getId();?></h2>
</div>

<!-- Start body content -->
<div class="body-content animated fadeIn">
    <div class="text-right">
        <div class="btn-group">
            <a class="btn btn-primary" href="<?= '/participant/' . $participant->getUniqueId() . '/adjustment';?>">
                <?=_("Back to participant transaction listing");?>
            </a>
        </div>
    </div>
    <br />
    <table class="table table-striped table-hover table-responsive">
        <thead>
            <tr>
                <th>ID</th>
                <th>Points</th>
                <th>Email</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?=$transaction->getId();?></td>
                <!-- @TODO: this can be done on the entity level, all entities should be hydrated with participant -->
                <td><?=bcmul($transaction->getTotal(), $participant->getProgram()->getPoint());?></td>
                <td><?=$transaction->getEmailAddress();?></td>
                <td><?=$transaction->getCreatedAt();?></td>
            </tr>
        </tbody>
    </table>
    <table class="table table-striped table-hover table-responsive">
        <thead>
        <tr>
            <th>Quantity</th>
            <th>Points</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($transaction->getItems() as $item):?>
            <?php /** @var \Entities\TransactionItem $item */?>
            <?php $product = $transaction->getProduct($item->getReferenceId());?>
            <tr>
                <td><?=$item->getQuantity();?></td>
                <td><?=bcmul(bcmul($product->getPrice(), $item->getQuantity(), 2), $participant->getProgram()->getPoint());?></td>
                <td><?=$product->getName();?></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>