<?php
/**
 * @var string $baseUrl
 */
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-star"></i>Organizations</h2>
</div>
<!-- Start body content -->
<div class="body-content animated fadeIn dash">
    <div class="row">
        <div class="col-xs-12">
            <div class="btn-group pull-right" role="group" data-toggle="tooltip" data-placement="left" title="Add Organization">
                <a class="btn btn-success"
                   href="/organization/create">
                    <i class="fa fa-fw fa-plus-square"></i> New
                </a>
            </div>
        </div>

    </div>

    <br/>

    <div class="row">

        <div class="col-xs-12">
            <div class="organization-listing"
                 data-paginate-alias="organization-listing"
                 data-paginate-cache="600"
                 data-paginate-pulse="false"
                 data-paginate-type="infinity"
                 data-paginate-container=""
                 data-paginate-touchy="400"
                 data-paginate-query-prefix=""
                 data-paginate-per-page="30"
                 data-paginate-autoload="false"
                 data-paginate-autosearch="false"
                 data-paginate-url="/organization/list">
                <div class="paginated-search group-border-dashed">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" placeholder="Search by organization name"/>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group">
                                    <div class="paginator-submit btn btn-primary"
                                         data-toggle="tooltip"
                                         data-placement="left"
                                         title="Search existing Organizations">
                                        Search
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive table-color mb-20">
                    <table class="table hover">
                        <thead>
                        <tr>
                            <th width="5%">ID</th>
                            <th width="85%">Name</th>
                            <th width="5%">Programs</th>
                            <th width="5%">Actions</th>
                        </tr>
                        </thead>

                        <tbody class="paginated-container">

                        </tbody>
                    </table>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>

</div>