<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-user-circle-o"></i>Brands</h2>
</div>
<!-- Start body content -->
<div class="body-content animated fadeIn">
    <br/>

    <div class="row">

        <div class="col-xs-12">
            <div class="brand-listing"
                 data-paginate-alias="brand-listing"
                 data-paginate-cache="600"
                 data-paginate-pulse="false"
                 data-paginate-type="infinity"
                 data-paginate-container=""
                 data-paginate-touchy="400"
                 data-paginate-query-prefix=""
                 data-paginate-per-page="30"
                 data-paginate-autoload="false"
                 data-paginate-autosearch="false"
                 data-paginate-url="/brand/list">
                <div class="paginated-search brand-border-dashed">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" placeholder="Search by brand name"/>
                            </div>
                        </div>

                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="paginator-submit btn btn-primary">Search</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive table-color mb-20">
                    <table class="table hover">
                        <thead>
                        <tr>
                            <th width="5%">ID</th>
                            <th width="90%">Name</th>
                        </tr>
                        </thead>

                        <tbody class="paginated-container">

                        </tbody>
                    </table>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>

</div>