<form name="category" action="/category/create" method="post">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><span class="fa fa-pencil-square"></span> Add category</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Category Name<span><strong>*</strong></span></label>
                    <input autocomplete="off" type="text" class="form-control" name="name" value=""/>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Active <span><strong>*</strong></span></label>
                    <select autocomplete="off" class="form-control" name="active">
                        <option value="yes">Yes</option>
                        <option value="no">No</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-inverse pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
</form>