#!/usr/bin/env php
<?php

use Factories\LoggerFactory;

require __DIR__ . "/../cli-bootstrap.php";

// Establish JWT Auth Token for Product Catalog access...
$requestedScopes = $container->get('roles')['superadmin'];
$authentication = $container->get('authentication');
$user = new \Entities\User([
    'email_address' => 'rewardstack@alldigitalrewards.com',
    'id' => 0,
    'firstname' => 'Autoredemption',
    'lastname' => 'System'
]);
/**
 * @var \Services\Authentication\Token $token
 */
$token = $authentication->getToken();
$token->setRequestedScopes($requestedScopes);
$token->setToken($token->generateUserToken($user)['token']);


/** @var \Psr\Container\ContainerInterface $container */
$factory = new \Services\Scheduler\ServiceFactory($container);
$scheduler = $factory->getService();
$output = $scheduler->run();

/**
 * @var \Psr\Log\LoggerInterface $logger
 */
$logger = LoggerFactory::getInstance();
foreach ($output as $taskOutput) {
    $logger->info(
        $taskOutput['output'],
        ['task' => $taskOutput['task']]
    );
}
