#!/usr/bin/env php
<?php
require __DIR__ . "/../cli-bootstrap.php";
/** @var \Interop\Container\ContainerInterface $container */
$factory = new \Services\Program\ServiceFactory($container);
$programRepo = $factory->getProgramRepository();

$programCanceller = new \Services\Program\ProgramCanceller($programRepo);
$programCanceller->cancelExpiredPrograms();