#!/usr/bin/env bash

export ADMIN_PORT=${ADMIN_PORT:-80}
export ADMIN_AMQP_PORT=${ADMIN_AMQP_PORT:-15672}
export ADMIN_MYSQL_PORT=${ADMIN_MYSQL_PORT:-3306}
export NG_ADMIN_PORT=${NG_ADMIN_PORT:-81}
export RA_ENDPOINT=${RA_ENDPOINT:-"https://ra.staging.alldigitalrewards.com/api/"}
export XDEBUG_HOST=${XDEBUG_HOST:-"10.0.1.3"}

TTY=""

## CI sends BUILD_NUMBER env variable.
if [ ! -z "$BUILD_NUMBER" ]; then
    COMPOSE_FILE="ci"
    DOCKER_HOST="unix://var/run/docker.sock"
    # Disable pseudo TTY for CI
    TTY="-T"
fi

## Perhaps add something in here for Windows/WSL defaults.

UNAMESTR=`uname`
if [ "$UNAMESTR" == 'Linux' ] || [ "$UNAMESTR" == 'Darwin' ]; then
    COMPOSE="docker-compose -f docker-compose.yml"
else
    COMPOSE="winpty docker-compose -f docker-compose.yml"
fi


if [ $# -gt 0 ];then
    if [ "$1" == "exec" ]; then
        shift 1
        $COMPOSE exec $TTY \
            admin \
            sh -c "cd /var/www/html && $@"
    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html $TTY \
            admin \
            composer "$@"
    elif [ "$1" == "migrate" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html $TTY \
            admin \
            /var/www/html/vendor/robmorgan/phinx/bin/phinx $@ -c /var/www/html/phinx.php
    elif [ "$1" == "reset" ]; then
        shift 1
        $COMPOSE exec $TTY \
            admin \
            sh -c "cd /var/www/html && ./vendor/robmorgan/phinx/bin/phinx seed:run"
    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE exec $TTY \
            admin \
            sh -c "cd /var/www/html && ./vendor/robmorgan/phinx/bin/phinx seed:run && ./vendor/phpunit/phpunit/phpunit $@"
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi