version: '2'
services:
  ingress:
    image: nginx:alpine
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - adrnet
  admin:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
      - ./app/xdebug.ini:/etc/php/7.2/fpm/conf.d/xdebug.ini
      - ./app/startup.sh:/usr/local/bin/startup.sh
      - ./app/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
    expose:
      - 80
    ports:
      - 81:80
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST}"
      PHP_IDE_CONFIG: "serverName=admin"
      ENVIRONMENT: development
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: mpadmin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RA_ENDPOINT: "${RA_ENDPOINT}"
      RA_USERNAME: claim
      RA_PASSWORD: claim
      JWT_SECRET: password
      AMQP_HOST: admin-amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_EVENT_CHANNEL: mp-admin-events
      MONGO_HOST: mongodb://mongodb:27017
      MONGO_DB: marketplace-dev
      CATALOG_URL: http://product.catalog
      PROGRAM_CATALOG_URL: http://product.program-catalog
      FILESYSTEM: local
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      GOOGLE_CDN_BUCKET: "adrcdn"
      ENABLE_CRON: "1"
    networks:
      - adrnet
  ng-admin:
    image: gcr.io/green-talent-129607/ng-marketplace-admin:latest
    expose:
      - 80
    environment:
      MP_ADMIN_HOST: http://localhost
    networks:
      - adrnet
  admin-mysql:
    image: mariadb:10.2
    ports:
      - "${ADMIN_MYSQL_PORT}:3306"
    expose:
      - 3306
    volumes:
      - mpadmindb:/var/lib/mysql
      - ./mysqld.conf:/etc/mysql/conf.d/docker.cnf
      - ./app/sql/base.sql:/docker-entrypoint-initdb.d/base.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mpadmin
      MYSQL_USER: dbuser
      MYSQL_PASS: dbpass
    networks:
      - adrnet
  admin-amqp:
      image: rabbitmq:3-management
      ports:
        - "${ADMIN_AMQP_PORT}:15672"
      expose:
        - 5672
      networks:
        - adrnet
  fluentd:
    image: fluent/fluentd:stable
    volumes:
      - ../logs:/fluentd/log
    networks:
      - adrnet
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
    networks:
      - adrnet
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mpadmin_mongo:/data/db
    expose:
      - 27017
    networks:
      - adrnet
  product.catalog:
    image: gcr.io/green-talent-129607/catalog:latest
    expose:
      - 80
    environment:
      JWT_SECRET: password
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: catalog
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      VENDOR_DB_HOST: 35.226.18.191
      VENDOR_DB_USER: user_staging
      VENDOR_DB_PASS: nX&QZe*l89N5
      VENDOR_DB_NAME: adr_crm-dev
      ENVIRONMENT: development
      IMAGE_URL: http://product.image
    networks:
      - adrnet
  batch.facilitator:
    image: gcr.io/green-talent-129607/api-batch:latest
    expose:
      - 80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      REWARDSTACK_USERNAME: "test@alldigitalrewards.com"
      REWARDSTACK_PASSWORD: "password"
      REWARDSTACK_ENDPOINT: http://admin
      MYSQL_DB_HOST: admin-mysql
      MYSQL_DB_DATABASE: api-batch
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
      AMQP_HOST: admin-amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_PARTICIPANT_CHANNEL: api-batch-participant
      AMQP_PARTICIPANT_TASKRUNNER: /app/bin/batch-participant-taskrunner
      AMQP_PARTICIPANT_MAX_CONSUMER: 3
      AMQP_PARTICIPANT_CONSUMER_RUNTIME: 180
      AMQP_ISSUANCE_CHANNEL: api-batch-issuance
      AMQP_ISSUANCE_TASKRUNNER: /app/bin/batch-issuance-taskrunner
      AMQP_ISSUANCE_MAX_CONSUMER: 3
      AMQP_ISSUANCE_CONSUMER_RUNTIME: 180
    networks:
      - adrnet
  product.image:
    image: gcr.io/green-talent-129607/product-image:latest
    expose:
      - 80
    environment:
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: image
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      ENVIRONMENT: development
      FILESYSTEM: local
      JWT_SECRET: password
    networks:
      - adrnet
  product.program-catalog:
    image: gcr.io/green-talent-129607/program-catalog:latest
    expose:
      - 80
    environment:
      MYSQL_DB_HOST: admin-mysql
      MYSQL_DB_DATABASE: program-catalog
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
      REWARDSTACK_DB_HOST: admin-mysql
      REWARDSTACK_DB_DATABASE: mpadmin
      REWARDSTACK_DB_USERNAME: root
      REWARDSTACK_DB_PASSWORD: 123
      JWT_SECRET: password
      ENVIRONMENT: development
      REDIS_HOST: program-catalog-redis
      REDIS_PORT: 6379
      PROGRAM_CONFIG_URL: http://admin/api/program
      CATALOG_URL: http://product.catalog
      LOG_HOST: fluentd
      LOG_PORT: "24224"
    networks:
      - adrnet
  program-catalog-redis:
    image: redis:3.2
    expose:
      - 6379
    networks:
      - adrnet
  email.transaction:
    image: gcr.io/green-talent-129607/transaction-email:latest
    expose:
      - 80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST}"
      PHP_IDE_CONFIG: "serverName=transaction-email"
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      AMQP_HOST: amqp
      AMQP_PORT: 5672
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      MAILCATCHER_SMTP_HOST: mailcatcher
      MAILCATCHER_SMTP_USERNAME: "technology@alldigitalrewards.com"
      MAILCATCHER_SMTP_PASSWORD: password
      MAILCATCHER_SMTP_PORT: 1025
      EMAIL_FROM: "technology@alldigitalrewards.com"
      EMAIL_FROM_TO: Technology ADR
      MAILCATCHER_SMTP_TO: "batman@alldigitalrewards.com"
      MAILCATCHER_SMTP_TO_NAME: Bruce Wayne
      RA_USERNAME: claim
      RA_PASSWORD: claim
      RA_ENDPOINT: https://ra.staging.alldigitalrewards.com/api/
      TOKEN_ENDPOINT: "https://admin/token"
      TOKEN_USERNAME: "test@alldigitalrewards.com"
      TOKEN_PASSWORD: "password"
      TRANSACTION_ITEM_CHANNEL: transaction-item
      CATALOG_URL: http://product.catalog
      PROGRAM_CONFIG_URL: http://admin/api/program
      MYSQL_DB_PASSWORD: 123
      MYSQL_DB_HOST: admin-mysql
      MYSQL_DB_DATABASE: transaction-email
      MYSQL_DB_USERNAME: root
    networks:
      - adrnet
  avs-service:
    image: gcr.io/green-talent-129607/address-verification-service:latest
    expose:
      - 80
    ports:
      - 85:80
    environment:
      ENVIRONMENT: development
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: avs
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      LOG_HOST: fluentd
      LOG_PORT: 24224
      SMARTY_AUTH_ID: 0945d3f2-5eff-32f4-b4b2-158847ff5f54
      SMARTY_AUTH_TOKEN: YsaH5jHF6lAUQzq7mOLE
      SMARTY_INTL_URL: "https://international-street.api.smartystreets.com/verify"
    networks:
      - adrnet
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - adrnet
  program.content:
    image: gcr.io/green-talent-129607/program-content:latest
    expose:
      - 80
    environment:
      JWT_SECRET: password
      ENVIRONMENT: development
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: program-content
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      FILESYSTEM: local
      GOOGLE_IMAGE_PATH: "https://storage.googleapis.com/adrcdn/programcontent/"
    networks:
      - adrnet
  card.account:
    image: gcr.io/green-talent-129607/card-account-admin:latest
    expose:
      - 80
    environment:
      JWT_SECRET: password
      ENVIRONMENT: development
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: ca-admin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      LOG_HOST: fluentd
      LOG_PORT: "24224"
    networks:
      - adrnet
  report:
    image: gcr.io/green-talent-129607/report-api:latest
    expose:
      - 80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      MYSQL_DB_HOST: admin-mysql
      MYSQL_DB_DATABASE: report
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
      RS_DB_HOST: admin-mysql
      RS_DB_USER: root
      RS_DB_PASS: 123
      RS_DB_NAME: mpadmin
      CATALOG_URL: http://product.catalog
      FILESYSTEM: local
      TOKEN_ENDPOINT: "https://admin.adrqa.info/token"
      TOKEN_USERNAME: "test@alldigitalrewards.com"
      TOKEN_PASSWORD: "password"
      AMQP_HOST: report-amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_CHANNEL: reports-pending-processing-queue
      AMQP_TASKRUNNER: /app/bin/pending-report-task-runner
      AMQP_MAX_CONSUMER: 3
      AMQP_CONSUMER_RUNTIME: 180
    networks:
      - adrnet
volumes:
  mpadmindb:
    driver: local
  mpadmin_mongo:
    driver: local
networks:
  adrnet:
    driver: "bridge"
