version: '2'
services:
  ingress:
    container_name: ingress
    depends_on:
      - admin
      - ng-admin
      - mysql
      - redis
      - amqp
      - mongodb
      - fluentd
      - mailcatcher
      - product.catalog
      - batch.facilitator
      - product.image
      - email.transaction
      - avs-service
      - ssn
      - program.content
      - card.account
      - redemption-campaigns-service
      - report
      - program.participant
    image: nginx:alpine
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - adrnet
  admin:
    depends_on:
      - mysql
    container_name: admin
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ../:/app
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.in
      - ./app/startup.sh:/usr/local/bin/startup.sh
      - ./app/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
    expose:
      - 80
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=default"
      ENVIRONMENT: development
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_HOST: mysql
      MYSQL_DATABASE: mpadmin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RA_ENDPOINT: "https://ra.staging.alldigitalrewards.com/api/"
      RA_USERNAME: claim
      RA_PASSWORD: claim
      JWT_SECRET: password
      AMQP_HOST: amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_EVENT_CHANNEL: mp-admin-events
      MONGO_HOST: mongodb://mongodb:27017
      MONGO_DB: marketplace-dev
      CATALOG_URL: http://product.catalog
      PROGRAM_CATALOG_URL: http://product.catalog
      FILESYSTEM: local
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      GOOGLE_CDN_BUCKET: "adrcdn_qa"
      ENABLE_CRON: "1"
      IP_WHITELIST: "207.192.244.170"
    networks:
      - adrnet
  ng-admin:
    image: gcr.io/green-talent-129607/mpadmin-ui:latest
    expose:
      - 80
    environment:
      MP_ADMIN_HOST: http://localhost
    networks:
      - adrnet
  mysql:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mpadmindb:/var/lib/mysql
      - ./mysqld.conf:/etc/mysql/conf.d/docker.cnf
      - ./app/sql/base.sql:/docker-entrypoint-initdb.d/base.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mpadmin
      MYSQL_USER: dbuser
      MYSQL_PASS: dbpass
    networks:
      - adrnet
  amqp:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    expose:
      - 5672
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log [{console,[{enabled,true},{level,warning}]}]"
    networks:
      - adrnet
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - adrnet
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mpadmin_mongo:/data/db
    expose:
      - 27017
    networks:
      - adrnet
  fluentd:
    image: fluent/fluentd:stable
    volumes:
      - ../logs:/fluentd/log
    networks:
      - adrnet
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - adrnet
  product.catalog:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/catalog:latest
    expose:
      - 80
    environment:
      JWT_SECRET: password
      MYSQL_HOST: mysql
      MYSQL_DATABASE: catalog
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      VENDOR_DB_HOST: 35.226.18.191
      VENDOR_DB_USER: user_staging
      VENDOR_DB_PASS: nX&QZe*l89N5
      VENDOR_DB_NAME: adr_crm-dev
      REWARDSTACK_DB_HOST: mysql
      REWARDSTACK_DB_USERNAME: root
      REWARDSTACK_DB_PASSWORD: 123
      REWARDSTACK_DB_DATABASE: mpadmin
      ENVIRONMENT: development
      IMAGE_URL: http://product.image
    networks:
      - adrnet
  batch.facilitator:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/api-batch:latest
    expose:
      - 80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      REWARDSTACK_USERNAME: "test@alldigitalrewards.com"
      REWARDSTACK_PASSWORD: "password"
      REWARDSTACK_ENDPOINT: http://admin
      MYSQL_DB_HOST: mysql
      MYSQL_DB_DATABASE: api-batch
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
      AMQP_HOST: amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_PARTICIPANT_CHANNEL: api-batch-participant
      AMQP_PARTICIPANT_TASKRUNNER: /app/bin/batch-participant-taskrunner
      AMQP_PARTICIPANT_MAX_CONSUMER: 3
      AMQP_PARTICIPANT_CONSUMER_RUNTIME: 180
      AMQP_ISSUANCE_CHANNEL: api-batch-issuance
      AMQP_ISSUANCE_TASKRUNNER: /app/bin/batch-issuance-taskrunner
      AMQP_ISSUANCE_MAX_CONSUMER: 3
      AMQP_ISSUANCE_CONSUMER_RUNTIME: 180
    networks:
      - adrnet
  product.image:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/product-image:latest
    expose:
      - 80
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: image
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      ENVIRONMENT: development
      FILESYSTEM: local
      JWT_SECRET: password
    networks:
      - adrnet
  email.transaction:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/transaction-email:latest
    expose:
      - 80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=transaction-email"
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      AMQP_HOST: amqp
      AMQP_PORT: 5672
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      MAILCATCHER_SMTP_HOST: mailcatcher
      MAILCATCHER_SMTP_USERNAME: "technology@alldigitalrewards.com"
      MAILCATCHER_SMTP_PASSWORD: password
      MAILCATCHER_SMTP_PORT: 1025
      EMAIL_FROM: "technology@alldigitalrewards.com"
      EMAIL_FROM_TO: Technology ADR
      MAILCATCHER_SMTP_TO: "batman@alldigitalrewards.com"
      MAILCATCHER_SMTP_TO_NAME: Bruce Wayne
      RA_USERNAME: claim
      RA_PASSWORD: claim
      RA_ENDPOINT: https://ra.staging.alldigitalrewards.com/api/
      TOKEN_ENDPOINT: "https://admin/token"
      TOKEN_USERNAME: "test@alldigitalrewards.com"
      TOKEN_PASSWORD: "password"
      TRANSACTION_ITEM_CHANNEL: transaction-item
      CATALOG_URL: http://product.catalog
      PROGRAM_CONFIG_URL: http://admin/api/program
      MYSQL_DB_HOST: mysql
      MYSQL_DB_DATABASE: transaction-email
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
    networks:
      - adrnet
  avs-service:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/address-verification-service:latest
    expose:
      - 80
    ports:
      - 85:80
    environment:
      ENVIRONMENT: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: avs
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      LOG_HOST: fluentd
      LOG_PORT: 24224
      SMARTY_AUTH_ID: 0945d3f2-5eff-32f4-b4b2-158847ff5f54
      SMARTY_AUTH_TOKEN: YsaH5jHF6lAUQzq7mOLE
      SMARTY_INTL_URL: "https://international-street.api.smartystreets.com/verify"
    networks:
      - adrnet
  ssn:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/ssn-service:latest
    expose:
      - 80
    ports:
      - 87:80
    environment:
      JWT_SECRET: password
      ENVIRONMENT: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ssn
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
    networks:
      - adrnet
  program.content:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/program-content:latest
    expose:
      - 80
    environment:
      JWT_SECRET: password
      ENVIRONMENT: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: program-content
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      FILESYSTEM: local
      GOOGLE_IMAGE_PATH: "https://storage.googleapis.com/adrcdn/programcontent/"
    networks:
      - adrnet
  card.account:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/card-account-admin:latest
    expose:
      - 80
    environment:
      JWT_SECRET: password
      ENVIRONMENT: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ca-admin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      LOG_HOST: fluentd
      LOG_PORT: "24224"
    networks:
      - adrnet
  program.participant:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/program-participant-service:latest
    expose:
      - 80
    environment:
        ENVIRONMENT: development
        JWT_SECRET: password
        MYSQL_HOST: mysql
        MYSQL_DATABASE: pps
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: 123
        ENCRYPTION_KEY: "C6628FC08A14232D145AE9FF79475D958447C3F7EE96DEC71ED3CFF4A5905756"
    networks:
      - adrnet
  redemption-campaigns-service:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/redemption-campaign-service:latest
    ports:
      - "89:80"
    environment:
      JWT_SECRET: password
      ENVIRONMENT: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: rcs_admin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      LOG_HOST: fluentd
      LOG_PORT: "24224"
      FILESYSTEM: local
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROGRAM_CONTENT_URL: http://program.content
      GOOGLE_IMAGE_PATH: "https://storage.googleapis.com/adrcdn/programcontent"
      GOOGLE_CDN_BUCKET: "adrcdn"
      STACKDRIVER_KEYFILE: >
        {
          "type": "service_account",
          "project_id": "green-talent-129607",
          "private_key_id": "ccb27667ebdfa9d75271e90b83d8ce5c6ce22d4e",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDWatATVzPqTUqD\nmWSxZ6bmw1uyZHulPaOlcpJxckeoELxUKs3U258iubJm2g/eHE3iKuRjRxnSX9ge\nTnWCV7Ed+7xVSL15Ijl/VNjQnGmc+LMyJABYOSeLgZJk3abSntNHlnXJCUYuXMns\nqReWetnOGrpY7IpDXxh7nH6uIKh96VrA8mOZXw4dQPMfjZacC7e1BDwZkPja+nnO\nD28tBja1lXmkbwM0S6u8jAOHhMMIVj+kfHgwZdUtSI0GIlMimbyTBZQ0iWR/EtYy\nZxHH07/GTkso2w7iT8y4WaXygQg1Vc1q7Xr3OpwdTiOSsxS36FTZsZuloIQAjs+6\nLt94UXmjAgMBAAECggEAM2c9Bf34aLnp3L3H+Y3nYdhA4fYb/GPYGSBsAj2K9zw3\n4he268pRDtKk9epeNnnjpA5zXWecxaYLmkxl+H8Ma6s/ndSH9APj8+ZD6lMtMKAg\n2aru2Devhs7j6UGILmM8NKPaDf2msRO2pwFssbs2/yXCOfJPPVKNfIjqh9U1f6Wj\nHmIAfQzm9WxopiuhA2Ago6XGkNT7yIlev1eKPB+E//aQsVLBL9ajHeN71PS2n7gG\nr8bZsgZqauq3H55f9xXHqGPxqbffi01W3Y8unwfOmO1+WbNvUwb8Ka2/o8n7ajMb\nXwljAFwl39Yr3qSib/8oVVPhU2y+r+LPB1FKsNgMOQKBgQDzDOiIouGfYgy9P1Zb\nwKWLnbNeCSOkCRwV8WyM8zmYdzxQCMy/bVO3URAI99o4glB35rOZIy3p8ZvIqKax\nIvYTWxWaGlSEc881IwzZ8WUH83jLBZGuzQ6haamjxCUm3285JQjJ8jvh3YnK8U6v\nhANrCdM3rkJ06lnu8NNlW3ISawKBgQDh11yKUNtuapew6LVbcc4LgdRvtnGbSDEX\nwAUJSZmiAfh25j53D3h/TLQjz1dzGBooPIZ9pjtPFY+/RJYHAzx6ASPEE+A1VL4y\nTfXnBFVSdL504kDgsMpFLeO6XZWhWMrg6q0rdIo5Gs3CuwOb3cN9R3x0QU65gnRY\nA6z+pwgzqQKBgEiML9SpGcOjVr4ea76TcFaOSf3lqHfMKE/8cjRYXXa/EIerOMJi\n9bwgPDMRGFgJvc8sU6uALrJH5gItJSR2lREN/RK0jUnD77OitLFRNqD68bFYBjYx\nCw7vJS223IgP5XkfLtJotasjn3+uK5iERSjsE9no7/lKAnIp/E+izhflAoGBAKGq\niwIwc4QNJd1sGDcHtpmiLLJzhcvE1+/Kc1B8sU+53WUv2NNd7cIi5GkmCdHIFSFs\nglH750TriGVA8ay/clFb84BvQfarXSOhjz/6aCGIlLYTKKIvq/vtp7FHQM+pQkHT\nfHc5C6FpQJX/TcwL6d8Kh1qpTXOaoTJIH1SDuWlRAoGBAIJJ1FXCedMYX/H9uUDe\nMi5OBwkHvqOe86eq2xm3tlIYXs7uPw4hAI5qK+3EJ85z+UEFR/RQrESx2QIBIQTg\ni3jsm8tAGoB27h7Px0YR5fcL1kc4rxz3lK0GiCOWwrtQXR+cnc58bpn6HE2XtSIA\nM+hyDESZkrM9TVo9wB+bpczA\n-----END PRIVATE KEY-----\n",
          "client_email": "sharecare-ssn-service-logger@green-talent-129607.iam.gserviceaccount.com",
          "client_id": "107811350151032697607",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sharecare-ssn-service-logger%40green-talent-129607.iam.gserviceaccount.com"
        }
    networks:
      - adrnet
  report:
    depends_on:
      - mysql
    image: gcr.io/green-talent-129607/report-api:latest
    expose:
      - 80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      MYSQL_DB_HOST: mysql
      MYSQL_DB_DATABASE: report
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
      RS_DB_HOST: mysql
      RS_DB_USER: root
      RS_DB_PASS: 123
      RS_DB_NAME: mpadmin
      CATALOG_URL: http://product.catalog
      FILESYSTEM: local
      TOKEN_ENDPOINT: "https://admin.adrqa.info/token"
      TOKEN_USERNAME: "test@alldigitalrewards.com"
      TOKEN_PASSWORD: "password"
      AMQP_HOST: report-amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_CHANNEL: reports-pending-processing-queue
      AMQP_TASKRUNNER: /app/bin/pending-report-task-runner
      AMQP_MAX_CONSUMER: 3
      AMQP_CONSUMER_RUNTIME: 180
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - adrnet
volumes:
  mpadmindb:
    driver: local
  mpadmin_mongo:
    driver: local
networks:
  adrnet:
    driver: "bridge"
