version: '2'
services:
  ingress:
    image: nginx:alpine
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - adrnet
  admin:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
      - ./app/xdebug.ini:/etc/php/7.2/fpm/conf.d/xdebug.ini
      - ./app/startup.sh:/usr/local/bin/startup.sh
      - ./app/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
      - ./app/crontab:/etc/crontab
    expose:
      - 80
    ports:
      - 81:80
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST}"
      PHP_IDE_CONFIG: "serverName=admin"
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_HOST: admin-mysql
      MYSQL_DATABASE: mpadmin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      RA_ENDPOINT: "${RA_ENDPOINT}"
      RA_USERNAME: claim
      RA_PASSWORD: claim
      JWT_SECRET: password
      AMQP_HOST: admin-amqp
      AMQP_PORT: "5672"
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_EVENT_CHANNEL: mp-admin-events
      MONGO_HOST: mongodb://mongodb:27017
      MONGO_DB: marketplace-dev
      CATALOG_URL: http://product.catalog
      FILESYSTEM: local
      LOG_HOST: fluentd
      LOG_PORT: "24224"
    networks:
      - adrnet
  ng-admin:
    image: gcr.io/green-talent-129607/ng-marketplace-admin:latest
    expose:
      - 80
    environment:
      MP_ADMIN_HOST: http://localhost
    networks:
      - adrnet
  admin-mysql:
    image: mysql:latest
    ports:
      - "${ADMIN_MYSQL_PORT}:3306"
    expose:
      - 3306
    volumes:
      - mpadmindb:/var/lib/mysql
      - ./mysqld.conf:/etc/mysql/conf.d/docker.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mpadmin
      MYSQL_USER: dbuser
      MYSQL_PASS: dbpass
    networks:
      - adrnet
  admin-amqp:
      image: rabbitmq:3-management
      ports:
        - "${ADMIN_AMQP_PORT}:15672"
      expose:
        - 5672
      networks:
        - adrnet
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mpadmin_mongo:/data/db
    expose:
      - 27017
    networks:
      - adrnet
  product.catalog:
    image: gcr.io/green-talent-129607/catalog:latest
    expose:
      - 80
    environment:
      MYSQL_HOST: catalog-mysql
      MYSQL_DATABASE: catalog
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      JWT_SECRET: password
      VENDOR_DB_HOST: 35.226.18.191
      VENDOR_DB_USER: user_staging
      VENDOR_DB_PASS: nX&QZe*l89N5
      VENDOR_DB_NAME: adr_crm-dev
      ENVIRONMENT: development
      IMAGE_URL: http://product.image
    networks:
      - adrnet
  catalog-mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: catalog
    networks:
      - adrnet
  product.image:
    image: gcr.io/green-talent-129607/product-image:latest
    expose:
      - 80
    environment:
      MYSQL_HOST: product-image-mysql
      MYSQL_DATABASE: image
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      ENVIRONMENT: development
      FILESYSTEM: local
      JWT_SECRET: password
    networks:
      - adrnet
  product-image-mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: image
    networks:
      - adrnet
  product.program-catalog:
    image: gcr.io/green-talent-129607/program-catalog:latest
    expose:
      - 80
    environment:
      MYSQL_DB_HOST: program-catalog-mysql
      MYSQL_DB_DATABASE: program-catalog
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 123
      JWT_SECRET: password
      ENVIRONMENT: development
      REDIS_HOST: program-catalog-redis
      REDIS_PORT: 6379
      PROGRAM_CONFIG_URL: http://admin/api/program
      CATALOG_URL: http://product.catalog
      LOG_HOST: fluentd
      LOG_PORT: "24224"
    networks:
      - adrnet
  program-catalog-mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: program-catalog
    networks:
      - adrnet
  program-catalog-redis:
    image: redis:3.2
    expose:
      - 6379
    networks:
      - adrnet
  fluentd:
    image: fluent/fluentd:stable
    volumes:
      - ../logs:/fluentd/log
    networks:
      - adrnet
volumes:
  mpadmindb:
    driver: local
  mpadmin_mongo:
    driver: local
networks:
  adrnet:
    driver: "bridge"