<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-th-large"></i>Products</h2>
</div>
<!-- Start body content -->
<div class="body-content animated fadeIn">
    <div class="row">

        <div class="col-xs-12">
            <div class="product-listing"
                 data-paginate-alias="product-listing"
                 data-paginate-cache="600"
                 data-paginate-pulse="false"
                 data-paginate-type="infinity"
                 data-paginate-container=""
                 data-paginate-touchy="400"
                 data-paginate-query-prefix=""
                 data-paginate-per-page="30"
                 data-paginate-autoload="false"
                 data-paginate-autosearch="false"
                 data-paginate-url="/product/list">
                <div class="paginated-search product-border-dashed">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" placeholder="Search by product name"/>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <select name="active" class="form-control">
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="paginator-submit btn btn-primary">Search</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive table-color mb-20">
                    <table class="table hover">
                        <thead>
                        <tr>
                            <th width="5%">ID</th>
                            <th width="80%">Name</th>
                            <th width="10%">Total</th>
                            <th width="5%">Actions</th>
                        </tr>
                        </thead>

                        <tbody class="paginated-container">

                        </tbody>
                    </table>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>

</div>