<?php
/**
 * @var \Entities\User $user
 * @var string $baseUrl
 */
?>
<table width="100%" cellpadding="0" cellspacing="0" border="0" data-mobile="true" dir="ltr" align="center"
       data-width="600" style="background-color: rgb(255, 255, 255);">
    <tbody>
    <tr>
        <td align="center" valign="top" style="padding:0;margin:0;">
            <div class="WRAPPER" style="max-width: 600px; margin: auto;">
                <table align="center" bgcolor="#ffffff" border="0" cellspacing="0" cellpadding="0" width="600"
                       class="wrapper" style="width: 600px;">
                    <tbody>
                    <tr>
                        <td align="left" valign="top" style="margin:0;padding:0;">

                            <table border="0" cellpadding="0" cellspacing="0" align="center" data-editable="image"
                                   data-mobile-stretch="1" width="100%" style="max-width: 100% !important;">
                                <tbody>
                                <tr>
                                    <td valign="top" align="left"
                                        style="display: inline-block; padding: 0px 0px 20px; margin: 0px;"
                                        class="tdBlock">
                                        <img src="/resources/app/images/email-header.png"
                                             width="600"
                                             data-src="/resources/app/images/email-header.png"
                                             data-origsrc="/resources/app/images/email-header.png"
                                             style="border-width: 0px; border-style: none; border-color: transparent; font-size: 12px; display: block; width: 100%; max-width: 100% !important;">
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="left" valign="top" style="margin:0;padding:0;">

                            <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center"
                                   data-editable="text" class="text-block">
                                <tbody>
                                <tr>
                                    <td align="left" valign="top" class="lh-1"
                                        style="padding: 0px 25px 15px; margin: 0px; font-family: Arial, Helvetica, sans-serif; color: rgb(38, 38, 38); font-size: 16px; line-height: 1.15;">
                                        <font style="font-size: 16px;" size="16">
                                            Hi, <br /> <br />
                                            Welcome to the Sharecare Administrator!<br>
                                        </font>
                                        <div><font style="font-size: 16px;" size="16"><br></font></div>
                                        <div><span style="font-weight: bold;">To Log-in:</span><br><br></div>
                                        <div>
                                            Click the button below to set up your Sharecare Marketplace Admin profile:
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top" style="margin: 0px; padding: 0px 0px 10px;">
                            <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%"
                                   data-editable="line" style="">
                                <tbody>
                                <tr>
                                    <td valign="top" align="center" style="padding: 10px 0px; margin: 0px;">
                                        <div style="height: 1px; line-height: 1px; border-top: 3px solid transparent;">
                                            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
                                                 alt="" width="1" height="1" style="display:block;" createnew="true">
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top" style="padding: 0px;">
                            <div data-box="button"
                                 style="width: 100%; margin-top: 0px; margin-bottom: 0px; text-align: center;">
                                <table border="0" cellpadding="0" cellspacing="0" align="center" data-editable="button"
                                       style="margin: 0px auto;">
                                    <tbody>
                                    <tr>
                                        <td valign="top" align="center" class="tdBlock"
                                            style="display: inline-block; padding: 13px 25px; margin: 0px; background-color: rgb(30, 183, 154); border-radius: 0px; width: 287px;">
                                            <a href="/invite?token=<?= $user->getInviteToken(); ?>"
                                               style="font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; color: rgb(255, 255, 255); font-size: 18px; text-decoration: none; font-weight: bold;"
                                               target="_blank">Set Up My Admin</a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top" style="margin: 0px; padding: 0px 0px 10px;">
                            <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%"
                                   data-editable="line" style="">
                                <tbody>
                                <tr>
                                    <td valign="top" align="center" style="padding: 10px 0px; margin: 0px;">
                                        <div style="height: 1px; line-height: 1px; border-top: 3px solid transparent;">
                                            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
                                                 alt="" width="1" height="1" style="display:block;" createnew="true">
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top" style="margin: 0px; padding: 0px;">
                            <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center"
                                   data-editable="text" class="text-block">
                                <tbody>
                                <tr>
                                    <td align="left" valign="top" class="lh-1"
                                        style="padding: 15px 25px 10px; font-size: 16px; font-family: Times New Roman, Times, serif; line-height: 1.15;">
                                        <span style="font-family: Arial, Helvetica Neue, Helvetica, sans-serif; background-color: transparent;">
                                            Please reference the Client Admin Training Guide for what the Admin can do for you.
                                        </span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </td>
    </tr>
    </tbody>
</table>
