<!DOCTYPE html>
<html class="bg-black">
<head>
    <meta charset="UTF-8">
    <title>Marketplace Administration | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- font style -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet">
    <link href="/resources/bower/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/resources/bower/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/resources/bower/jquery.gritter/css/jquery.gritter.css" rel="stylesheet">
    <link href="/resources/app/css/reset.css" rel="stylesheet">
    <link href="/resources/app/css/layout.css" rel="stylesheet">
    <link href="/resources/app/css/components.css" rel="stylesheet">
    <link href="/resources/app/css/plugins.css" rel="stylesheet">
    <link href="/resources/app/css/theme.css" rel="stylesheet">
    <link href="/resources/app/css/custom.css" rel="stylesheet">
    <link href="/resources/app/css/pages/sign.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="bg-dark">

<!-- START @WRAPPER-->
<div id="wrapper">

    <!-- START @SIGN WRAPPER -->
    <div id="sign-wrapper">

        <?php if (!empty($flash['warning'])) : ?>
            <?php foreach($flash['warning'] as $message):?>

            <div class="alert text-danger text-center"><i class="fa fa-minus-circle"></i> <strong><?=$message;?></strong></div>

            <?php endforeach;?>
        <?php endif; ?>

        <?php if (!empty($flash['success'])) : ?>
            <?php foreach($flash['success'] as $message):?>

                <div class="alert text-success text-center"><i class="fa fa-minus-circle"></i> <strong><?=$message;?></strong></div>

            <?php endforeach;?>
        <?php endif; ?>

        <!-- Login form -->
        <form id="sign-in" class="form-horizontal animated zoomIn shadow rounded" method="post">
            <div class="sign-header">
                <div class="form-group">
                    <div class="sign-text">
                        <span>Administration Area</span>
                    </div>
                </div><!-- /.form-group -->
            </div><!-- /.sign-header -->
            <div class="sign-body">
                <div class="form-group">
                    <div class="input-group input-group-lg rounded">
                        <input type="text" class="form-control input-sm" placeholder="Email Address" name="email_address">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    </div>
                </div><!-- /.form-group -->
                <div class="form-group">
                    <div class="input-group input-group-lg rounded">
                        <input type="password" class="form-control input-sm" placeholder="Password" name="password">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    </div>
                </div><!-- /.form-group -->
            </div><!-- /.sign-body -->
            <div class="sign-footer">
                <div class="form-group">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="ckbox ckbox-theme">
                                <input id="rememberme" type="checkbox" value="1" name="remember_me">
                                <label for="rememberme" class="rounded">Remember me</label>
                            </div>
                        </div>
                        <div class="col-xs-6 text-right">
                            <a href="/user/recovery" title="lost password">Lost password?</a>
                        </div>
                    </div>
                </div><!-- /.form-group -->
                <div class="form-group">
                    <button type="submit" class="btn btn-theme btn-lg btn-block no-margin rounded" id="login-btn">Sign In</button>
                </div><!-- /.form-group -->
            </div><!-- /.sign-footer -->
        </form><!-- /.form-horizontal -->
        <!--/ Login form -->
        <!--/ Content text -->

    </div><!-- /#sign-wrapper -->
    <!--/ END SIGN WRAPPER -->
</div><!-- /#wrapper -->
<!--/ END WRAPPER-->

<script src="/resources/bower/jquery/dist/jquery.min.js"></script>
<script src="/resources/bower/bootstrap/dist/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function() {
        $('#sign-wrapper').css('min-height', $(window).outerHeight());
    });
</script>
</body>
</html>
