<div style="position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  -o-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);

  font-size: 20px;
  background-color: cyan;
  border: darkgreen 5px solid;
  padding: 5px;">

    <h1>Whoops! Page Not Found</h1>

    <h2>Well.. this is strange.</h2>
    <p>
        It seems you've landed here by accident. <br />
        If this problem persist, please contact support. <br />
        <a href="mailto:csr@alldigitalrewards.com">csr@alldigitalrewards.com</a>
    </p>
</div>