<?php
/**
 *
 * @var \Services\Authentication\Authenticate $auth
 * @var string $baseUrl
 * @var string $formAction
 * @var string $formContext update or create
 * @var \Entities\User $user
 */
$updateFormSuccess = _('User updated');
$createFormSuccess = _('User created. Redirecting...');
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-gears"></i><?=$formContext === 'update' ? 'Update':'Add';?> User</h2>
</div>

<!-- Start body content -->
<div class="body-content animated fadeIn">

    <div class="message"></div>
    <form name="user"
          data-action-type="<?=$formContext;?>"
          data-success-create-message="<?=$createFormSuccess;?>"
          data-success-update-message="<?=$updateFormSuccess;?>"
          action="<?=  $formAction; ?>"
          method="post">

        <fieldset>
            <legend>User</legend>

            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Organization <span><strong>*</strong></span></label>
                        <select autocomplete="off"
                                name="organization"
                                data-offset="30"
                                data-unique-id="true"
                                data-min-characters="0"
                                class="form-control"
                                data-remote="/organization/list?method=json">
                            <?php if($user->getOrganization() !== null):?>
                            <option selected value="<?=$user->getOrganization()->getUniqueId();?>"><?=$user->getOrganization()->getName();?></option>
                            <?php endif;?>
                        </select>
                    </div>
                </div>
                <?php if(in_array($auth->getUser()->getRole(), ['superadmin', 'admin'])):?>
                <div class="col-lg-4">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Role <span><strong>*</strong></span></label>
                            <select autocomplete="off" class="form-control" name="role">
                                <option <?=($user->getRole()!=='reports'?:'selected');?>
                                        value="reports">Reporting</option>
                                <option <?=($user->getRole()!=='configs'?:'selected');?>
                                        value="configs">Configuration</option>
                                <?php if($auth->getUser()->getRole() === 'superadmin') : ?>
                                    <option <?=($user->getRole()!=='admin'?:'selected');?>
                                            value="admin">Admin</option>
                                    <option <?=($user->getRole()!=='superadmin'?:'selected');?>
                                            value="superadmin">Super Admin</option>
                                <?php endif;?>
                            </select>
                        </div>
                    </div>
                </div>
                <?php endif;?>

                <div class="col-lg-1">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Status <span><strong>*</strong></span></label>
                            <select autocomplete="off" class="form-control" name="active">
                                <option value="1">Active</option>
                                <option <?=$user->isActive() === true ?:'selected';?> value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>First Name <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                            type="text"
                            class="form-control"
                            name="firstname"
                            value="<?=$user->getFirstname();?>"
                        />
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Last Name <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                            type="text"
                            class="form-control"
                            name="lastname"
                            value="<?=$user->getLastname();?>"
                        />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-8">
                    <div class="form-group">
                        <label>Email Address <span><strong>*</strong></span></label>
                        <input autocomplete="off"
                            type="text"
                            class="form-control"
                            name="email_address"
                            value="<?=$user->getEmailAddress();?>"
                        />
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="form-group">
                        <label>Password <?=$user->getId() !== null ?'':'<span><strong>*</strong></span>';?></label>
                        <input autocomplete="off"
                            type="text"
                            class="form-control"
                            name="password"
                            minlength="8"
                        />
                    </div>
                </div>
            </div>
        </fieldset>

        <div class="footer text-right">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
        <br/>
    </form>
</div>