<?php
/** @var string $baseUrl */
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-users"></i>Users</h2>
</div>
<!-- Start body content -->
<div class="body-content animated fadeIn">
    <div class="row">
        <div class="col-xs-12">
            <div class="btn-group pull-right"
                 role="group"
                 >

                <a class="btn btn-success" style="margin-right: 3px;" data-toggle="tooltip" data-placement="left" title="Add User" href="/user/create">
                    <i class="fa fa-fw fa-plus-square" ></i> New
                </a>

                <a class="btn btn-success" data-toggle="tooltip" data-placement="left" title="Upload user" href="/user/import/upload">
                    <i class="fa fa-fw fa-upload"></i> Upload
                </a>

            </div>
        </div>

    </div>

    <br/>

    <div class="row">

        <div class="col-xs-12">
            <?php $url =  '/user/list';?>
            <div class="user-listing"
                 data-paginate-alias="user-listing"
                 data-paginate-cache="600"
                 data-paginate-pulse="false"
                 data-paginate-type="infinity"
                 data-paginate-container=""
                 data-paginate-touchy="400"
                 data-paginate-query-prefix=""
                 data-paginate-per-page="30"
                 data-paginate-autoload="false"
                 data-paginate-autosearch="false"
                 data-paginate-url="<?= $url; ?>">
                <div class="paginated-search group-border-dashed">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <select autocomplete="off"
                                        name="organization"
                                        data-offset="30"
                                        data-unique-id
                                        data-min-characters="0"
                                        class="form-control"
                                        data-placeholder="Organization"
                                        data-remote="/organization/list?method=json">
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input autocomplete="off" type="text" name="name" class="form-control" placeholder="Name"/>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input autocomplete="off" type="text" name="email_address" class="form-control" placeholder="Email"/>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="form-group">
                                <select autocomplete="off" name="status" data-ignore-select="true" class="form-control">
                                    <option value="">Status: All</option>
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                        </div>
                        <div class="col√-md-2">
                            <div class="form-group">
                                <div class="paginator-submit btn btn-primary" data-toggle="tooltip" data-original-title="Search for existing user">Search</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive table-color">
                    <table class="table hover">
                        <thead>
                        <tr>

                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Actions</th>

                        </tr>
                        </thead>

                        <tbody class="paginated-container">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>