<?php
/**
 * @var string $baseUrl
 * @var string $currentReportCriteria
 * @var \Services\Report\Interfaces\Reportable $report
 */
?>
<!-- Content Header (Page header) -->
<div class="header-content">
    <h2><i class="fa fa-fw fa-gears"></i>Report: <?=$report->getReportName();?></h2>
</div>

<!-- Start body content -->
<div class="body-content animated fadeIn">
    <!-- Show filters -->
    <div class="text-right">
        <div class="btn-group">
            <a class="btn btn-default" data-toggle="tooltip" data-original-title="Create a new report" href="<?= '/report';?>" target="_blank">
                New Report
            </a>
            <a class="btn btn-primary" data-toggle="tooltip" data-original-title="Updating the criteria on the current report" href="<?= '/report?' . $currentReportCriteria . '&update=true';?>">
                Update criteria
            </a>
            <?php if($report->getPage() !== 1) : ?>
            <a class="btn btn-default"
               data-toggle="tooltip"
               data-original-title="Next Page"
               href="<?= '/report?' . $currentReportCriteria . '&page=' . ($report->getPage() - 1);?>">
                <span class="fa fa-fast-backward"></span>
                Prev Page
            </a>
            <?php endif; ?>
            <?php if(count($report->getReportData()) == \Services\Report\AbstractReport::RESULT_COUNT) : ?>
            <a class="btn btn-default"
               data-toggle="tooltip"
               data-original-title="Next Page"
               href="<?= '/report?' . $currentReportCriteria . '&page=' . ($report->getPage() + 1);?>">
                Next Page
                <span class="fa fa-fast-forward"></span>
            </a>
            <?php endif; ?>
        </div>
    </div>
    <br />
    <table class="table table-striped table-hover">
        <thead>
            <?php foreach($report->getReportHeaders() as $column): ?>
            <th><?=$column;?></th>
            <?php endforeach;?>
        </thead>
        <tbody>
        <?php foreach($report->getReportData() as $record): ?>
        <tr>
            <?php foreach($record as $element): ?>
            <td><?=$element;?></td>
            <?php endforeach;?>
        </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>